// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'inspector/intro',
      label: '¿Qué es?',
    },
    {
      type: 'category',
      label: 'Exploración visual (HTML + CSS)',
      items: [
        'inspector/panel-elementos',
        'inspector/panel-estilos',
        'inspector/panel-computado',
      ],
    },
    {
      type: 'category',
      label: 'Depuración y consola',
      items: [
        'inspector/panel-consola',
        'inspector/panel-fuentes',
      ],
    },
    {
      type: 'category',
      label: 'Red y rendimiento',
      items: [
        'inspector/panel-red',
        'inspector/panel-performance',
        'inspector/panel-memoria',
      ],
    },
    {
      type: 'category',
      label: 'Accesibilidad y SEO',
      items: [
        'inspector/panel-accesibilidad',
        'inspector/panel-lighthouse',
        'inspector/panel-seguridad',
      ],
    },
    {
      type: 'category',
      label: 'Herramientas extra',
      items: [
        'inspector/panel-aplicacion',
        'inspector/panel-dispositivos',
      ],
    },
  ],
   
};

export default sidebars;
